osx_image: xcode8
language: objective-c
before_install:
    - gem install xcpretty
script:
    - xcodebuild build -project Nora.xcodeproj -scheme Nora -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
